# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: BlueWing_ENVIRONMENT
    value: bluewing
  - name: RedWing_ENVIRONMENT
    value: redwing

stages:
  - stage: BlueWingResourcesPreparation
    jobs:
      - job: BlueWinResources
        pool:
          vmImage: "ubuntu-latest"
          environment: $(BlueWing_ENVIRONMENT)
        continueOnError: false
        steps:
          - task: PublishPipelineArtifact@1
            displayName: Publish Files to Pipeline
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/win365ent"
              artifact: "win365ent-out"
              publishLocation: "pipeline"
          

  - stage: MS365ENTResourcesPreparation
    jobs:
      - job: MS365ENTResources
        pool:
          vmImage: "ubuntu-latest"
          environment: $(RedWing_ENVIRONMENT)
        continueOnError: true
        steps:
          - task: PublishPipelineArtifact@1
            displayName: Publish Files to Pipeline
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/win365ent"
              artifact: "win365ent-out"
              publishLocation: "pipeline"
          

          - task: AzureCLI@2
            displayName: Create resources in BlueWing
            inputs:
              azureSubscription: 'bluewing-v588c-subsc'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group what-if --resource-group test-firewall-rg --template-file template.json --parameters parameters.json
                az deployment group create --resource-group test-firewall-rg --template-file template.json --parameters parameters.json
              workingDirectory: '$(System.DefaultWorkingDirectory)/win365ent'
          

  - stage: FirewallPolicyRules
    jobs:
      - job: FirewallPolicyRules
        pool:
          vmImage: "ubuntu-latest"
          environment: $(MS365ENT_ENVIRONMENT)
        continueOnError: true
        steps:
          - task: PublishPipelineArtifact@1
            displayName: Publish Files to Pipeline
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/firewall-policy"
              publishLocation: "pipeline"
          
          - task: AzureCLI@2
            displayName: Insert Firewall Policy Rules
            inputs:
              azureSubscription: 'bluewing-v588c-subsc'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group what-if --resource-group test-firewall-rg --template-file template.json --parameters parameters.json
                az deployment group create --resource-group test-firewall-rg --template-file template.json --parameters parameters.json
              workingDirectory: '$(System.DefaultWorkingDirectory)/firewall-policy'
          

