# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: MS365ENT_ENVIRONMENT
    value: ms365ent


stages:
  - stage: MS365ENTResourcesPreparation
    jobs:
      - job: MS365ENTResources
        pool:
          vmImage: "ubuntu-latest"
          environment: $(MS365ENT_ENVIRONMENT)
        continueOnError: false
        steps:
          - task: PublishPipelineArtifact@1
            displayName: Publish Files to Pipeline
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/ms365ent"
              artifact: "ms365ent-out"
              publishLocation: "pipeline"
          
          - task: AzureCLI@2
            displayName: What-If Check
            inputs:
              azureSubscription: 'win365ent-test-firewall-rg-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group what-if --resource-group test-firewall-rg --template-file 5firewall_route.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 6servicework_vm_nsg.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 6servicework_vm236.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 6servicework_vm.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 1ms365entvnet1fw.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 2firewall_ms365ent.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 3firewall_policy.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 4firewal_publicip.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 6servicework_vm236.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file shutdown_computevm_6servicework_vm.bicep
              workingDirectory: '$(System.DefaultWorkingDirectory)/win365ent'
          - task: AzureCLI@2
            displayName: Create resources in MS365ENT
            inputs:
              azureSubscription: 'win365ent-test-firewall-rg-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group what-if --resource-group test-firewall-rg --template-file 5firewall_route.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 6servicework_vm_nsg.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 6servicework_vm236.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 6servicework_vm.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 1ms365entvnet1fw.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 2firewall_ms365ent.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 3firewall_policy.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 4firewal_publicip.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file 6servicework_vm236.bicep
                az deployment group what-if --resource-group test-firewall-rg --template-file shutdown_computevm_6servicework_vm.bicep
              workingDirectory: '$(System.DefaultWorkingDirectory)/win365ent'
          

