# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: WIN365ENT_ENVIRONMENT
    value: win365ent


stages:
  - stage: WIN365ENTResourcesPreparation
    jobs:
      - job: WIN365ENTResources
        pool:
          vmImage: "ubuntu-latest"
          environment: $(WIN365ENT_ENVIRONMENT)
        continueOnError: false
        steps:
          - task: PublishPipelineArtifact@1
            displayName: Publish Files to Pipeline
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/win365ent"
              artifact: "ms365ent-out"
              publishLocation: "pipeline"
          


          - task: AzureCLI@2
            displayName: What-If Check
            inputs:
              azureSubscription: 'win365ent-test-firewall-rg-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group what-if --resource-group test-firewall-rg --template-file 4firewal-publicip.json --parameters 4firewall-publicparam.json
                az deployment group create --resource-group test-firewall-rg --template-file 4firewal-publicip.json --parameters 4firewall-publicparam.json
              workingDirectory: '$(System.DefaultWorkingDirectory)/win365ent'
          - task: AzureCLI@2
            displayName: Create resources in WIN365ENT
            inputs:
              azureSubscription: 'win365ent-test-firewall-rg-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group what-if --resource-group test-firewall-rg --template-file template.json --parameters parameters.json
                az deployment group create --resource-group test-firewall-rg --template-file 4firewal-publicip.json --parameters 4firewall-publicparam.json
              workingDirectory: '$(System.DefaultWorkingDirectory)/win365ent'
          

